INSERT INTO division (name)
VALUES ('Barisal'),
       ('Chattogram'),
       ('Dhaka'),
       ('Khulna'),
       ('Rajshahi'),
       ('Rangpur'),
       ('Sylhet'),
       ('Mymensingh');

INSERT INTO district (name, division_id)
VALUES ('Dhaka', 3),
       ('Faridpur', 3),
       ('Gazipur', 3),
       ('Gopalganj', 3),
       ('Jamalpur', 8),
       ('Kishoreganj', 3),
       ('Madaripur', 3),
       ('Manikganj', 3),
       ('Munshiganj', 3),
       ('Mymensingh', 8),
       ('Narayanganj', 3),
       ('Narsingdi', 3),
       ('Netrokona', 8),
       ('Rajbari', 3),
       ('Shariatpur', 3),
       ('Sherpur', 8),
       ('Tangail', 3),
       ('Bogura', 5),
       ('Joypurhat', 5),
       ('Naogaon', 5),
       ('Natore', 5),
       ('Nawabganj', 5),
       ('Pabna', 5),
       ('Rajshahi', 5),
       ('Sirajgonj', 5),
       ('Dinajpur', 6),
       ('Gaibandha', 6),
       ('Kurigram', 6),
       ('Lalmonirhat', 6),
       ('Nilphamari', 6),
       ('Panchagarh', 6),
       ('Rangpur', 6),
       ('Thakurgaon', 6),
       ('Barguna', 1),
       ('Barishal', 1),
       ('Bhola', 1),
       ('Jhalokati', 1),
       ('Patuakhali', 1),
       ('Pirojpur', 1),
       ('Bandarban', 2),
       ('Brahmanbaria', 2),
       ('Chandpur', 2),
       ('Chattogram', 2),
       ('Cumilla', 2),
       ('Cox''s Bazar', 2),
       ('Feni', 2),
       ('Khagrachari', 2),
       ('Lakshmipur', 2),
       ('Noakhali', 2),
       ('Rangamati', 2),
       ('Habiganj', 7),
       ('Maulvibazar', 7),
       ('Sunamganj', 7),
       ('Sylhet', 7),
       ('Bagerhat', 4),
       ('Chuadanga', 4),
       ('Jashore', 4),
       ('Jhenaidah', 4),
       ('Khulna', 4),
       ('Kushtia', 4),
       ('Magura', 4),
       ('Meherpur', 4),
       ('Narail', 4),
       ('Satkhira', 4);

INSERT INTO upazila (name, district_id)
VALUES ('Amtali', 34),
       ('Bamna', 34),
       ('Barguna Sadar', 34),
       ('Betagi', 34),
       ('Patharghata', 34),
       ('Taltali', 34),
       ('Muladi', 35),
       ('Babuganj', 35),
       ('Agailjhara', 35),
       ('Barisal Sadar', 35),
       ('Bakerganj', 35),
       ('Banaripara', 35),
       ('Gaurnadi', 35),
       ('Hizla', 35),
       ('Mehendiganj', 35),
       ('Wazirpur', 35),
       ('Bhola Sadar', 36),
       ('Burhanuddin', 36),
       ('Char Fasson', 36),
       ('Daulatkhan', 36),
       ('Lalmohan', 36),
       ('Manpura', 36),
       ('Tazumuddin', 36),
       ('Jhalokati Sadar', 37),
       ('Kathalia', 37),
       ('Nalchity', 37),
       ('Rajapur', 37),
       ('Bauphal', 38),
       ('Dashmina', 38),
       ('Galachipa', 38),
       ('Kalapara', 38),
       ('Mirzaganj', 38),
       ('Patuakhali Sadar', 38),
       ('Dumki', 38),
       ('Rangabali', 38),
       ('Bhandaria', 39),
       ('Kaukhali', 39),
       ('Mathbaria', 39),
       ('Nazirpur', 39),
       ('Nesarabad', 39),
       ('Pirojpur Sadar', 39),
       ('Zianagar', 39),
       ('Bandarban Sadar', 40),
       ('Thanchi', 40),
       ('Lama', 40),
       ('Naikhongchhari', 40),
       ('Ali kadam', 40),
       ('Rowangchhari', 40),
       ('Ruma', 40),
       ('Brahmanbaria Sadar', 41),
       ('Ashuganj', 41),
       ('Nasirnagar', 41),
       ('Nabinagar', 41),
       ('Sarail', 41),
       ('Shahbazpur Town', 41),
       ('Kasba', 41),
       ('Akhaura', 41),
       ('Bancharampur', 41),
       ('Bijoynagar', 41),
       ('Chandpur Sadar', 42),
       ('Faridganj', 42),
       ('Haimchar', 42),
       ('Haziganj', 42),
       ('Kachua', 42),
       ('Matlab Uttar', 42),
       ('Matlab Dakkhin', 42),
       ('Shahrasti', 42),
       ('Anwara', 43),
       ('Banshkhali', 43),
       ('Boalkhali', 43),
       ('Chandanaish', 43),
       ('Fatikchhari', 43),
       ('Hathazari', 43),
       ('Lohagara', 43),
       ('Mirsharai', 43),
       ('Patiya', 43),
       ('Rangunia', 43),
       ('Raozan', 43),
       ('Sandwip', 43),
       ('Satkania', 43),
       ('Sitakunda', 43),
       ('Barura', 44),
       ('Brahmanpara', 44),
       ('Burichong', 44),
       ('Chandina', 44),
       ('Chauddagram', 44),
       ('Daudkandi', 44),
       ('Debidwar', 44),
       ('Homna', 44),
       ('Comilla Sadar', 44),
       ('Laksam', 44),
       ('Monohorgonj', 44),
       ('Meghna', 44),
       ('Muradnagar', 44),
       ('Nangalkot', 44),
       ('Comilla Sadar South', 44),
       ('Titas', 44),
       ('Chakaria', 45),
       ('{{198}}''{{199}}', 45),
       ('Kutubdia', 45),
       ('Maheshkhali', 45),
       ('Ramu', 45),
       ('Teknaf', 45),
       ('Ukhia', 45),
       ('Pekua', 45),
       ('Feni Sadar', 46),
       ('Chagalnaiya', 46),
       ('Daganbhyan', 46),
       ('Parshuram', 46),
       ('Fhulgazi', 46),
       ('Sonagazi', 46),
       ('Dighinala', 47),
       ('Khagrachhari', 47),
       ('Lakshmichhari', 47),
       ('Mahalchhari', 47),
       ('Manikchhari', 47),
       ('Matiranga', 47),
       ('Panchhari', 47),
       ('Ramgarh', 47),
       ('Lakshmipur Sadar', 48),
       ('Raipur', 48),
       ('Ramganj', 48),
       ('Ramgati', 48),
       ('Komol Nagar', 48),
       ('Noakhali Sadar', 49),
       ('Begumganj', 49),
       ('Chatkhil', 49),
       ('Companyganj', 49),
       ('Shenbag', 49),
       ('Hatia', 49),
       ('Kobirhat', 49),
       ('Sonaimuri', 49),
       ('Suborno Char', 49),
       ('Rangamati Sadar', 50),
       ('Belaichhari', 50),
       ('Bagaichhari', 50),
       ('Barkal', 50),
       ('Juraichhari', 50),
       ('Rajasthali', 50),
       ('Kaptai', 50),
       ('Langadu', 50),
       ('Nannerchar', 50),
       ('Kaukhali', 50),
       ('Dhamrai', 1),
       ('Dohar', 1),
       ('Keraniganj', 1),
       ('Nawabganj', 1),
       ('Savar', 1),
       ('Faridpur Sadar', 2),
       ('Boalmari', 2),
       ('Alfadanga', 2),
       ('Madhukhali', 2),
       ('Bhanga', 2),
       ('Nagarkanda', 2),
       ('Charbhadrasan', 2),
       ('Sadarpur', 2),
       ('Shaltha', 2),
       ('Gazipur Sadar-Joydebpur', 3),
       ('Kaliakior', 3),
       ('Kapasia', 3),
       ('Sripur', 3),
       ('Kaliganj', 3),
       ('Tongi', 3),
       ('Gopalganj Sadar', 4),
       ('Kashiani', 4),
       ('Kotalipara', 4),
       ('Muksudpur', 4),
       ('Tungipara', 4),
       ('Dewanganj', 5),
       ('Baksiganj', 5),
       ('Islampur', 5),
       ('Jamalpur Sadar', 5),
       ('Madarganj', 5),
       ('Melandaha', 5),
       ('Sarishabari', 5),
       ('Narundi Police I.C', 5),
       ('Astagram', 6),
       ('Bajitpur', 6),
       ('Bhairab', 6),
       ('Hossainpur', 6),
       ('Itna', 6),
       ('Karimganj', 6),
       ('Katiadi', 6),
       ('Kishoreganj Sadar', 6),
       ('Kuliarchar', 6),
       ('Mithamain', 6),
       ('Nikli', 6),
       ('Pakundia', 6),
       ('Tarail', 6),
       ('Madaripur Sadar', 7),
       ('Kalkini', 7),
       ('Rajoir', 7),
       ('Shibchar', 7),
       ('Manikganj Sadar', 8),
       ('Singair', 8),
       ('Shibalaya', 8),
       ('Saturia', 8),
       ('Harirampur', 8),
       ('Ghior', 8),
       ('Daulatpur', 8),
       ('Lohajang', 9),
       ('Sreenagar', 9),
       ('Munshiganj Sadar', 9),
       ('Sirajdikhan', 9),
       ('Tongibari', 9),
       ('Gazaria', 9),
       ('Bhaluka', 10),
       ('Trishal', 10),
       ('Haluaghat', 10),
       ('Muktagachha', 10),
       ('Dhobaura', 10),
       ('Fulbaria', 10),
       ('Gaffargaon', 10),
       ('Gauripur', 10),
       ('Ishwarganj', 10),
       ('Mymensingh Sadar', 10),
       ('Nandail', 10),
       ('Phulpur', 10),
       ('Araihazar', 11),
       ('Sonargaon', 11),
       ('Bandar', 11),
       ('Naryanganj Sadar', 11),
       ('Rupganj', 11),
       ('Siddirgonj', 11),
       ('Belabo', 12),
       ('Monohardi', 12),
       ('Narsingdi Sadar', 12),
       ('Palash', 12),
       ('Raipura, Narsingdi', 12),
       ('Shibpur', 12),
       ('Kendua Upazilla', 13),
       ('Atpara Upazilla', 13),
       ('Barhatta Upazilla', 13),
       ('Durgapur Upazilla', 13),
       ('Kalmakanda Upazilla', 13),
       ('Madan Upazilla', 13),
       ('Mohanganj Upazilla', 13),
       ('Netrakona-S Upazilla', 13),
       ('Purbadhala Upazilla', 13),
       ('Khaliajuri Upazilla', 13),
       ('Baliakandi', 14),
       ('Goalandaghat', 14),
       ('Pangsha', 14),
       ('Kalukhali', 14),
       ('Rajbari Sadar', 14),
       ('Shariatpur Sadar -Palong', 15),
       ('Damudya', 15),
       ('Naria', 15),
       ('Jajira', 15),
       ('Bhedarganj', 15),
       ('Gosairhat', 15),
       ('Jhenaigati', 16),
       ('Nakla', 16),
       ('Nalitabari', 16),
       ('Sherpur Sadar', 16),
       ('Sreebardi', 16),
       ('Tangail Sadar', 17),
       ('Sakhipur', 17),
       ('Basail', 17),
       ('Madhupur', 17),
       ('Ghatail', 17),
       ('Kalihati', 17),
       ('Nagarpur', 17),
       ('Mirzapur', 17),
       ('Gopalpur', 17),
       ('Delduar', 17),
       ('Bhuapur', 17),
       ('Dhanbari', 17),
       ('Bagerhat Sadar', 55),
       ('Chitalmari', 55),
       ('Fakirhat', 55),
       ('Kachua', 55),
       ('Mollahat', 55),
       ('Mongla', 55),
       ('Morrelganj', 55),
       ('Rampal', 55),
       ('Sarankhola', 55),
       ('Damurhuda', 56),
       ('Chuadanga-S', 56),
       ('Jibannagar', 56),
       ('Alamdanga', 56),
       ('Abhaynagar', 57),
       ('Keshabpur', 57),
       ('Bagherpara', 57),
       ('Jessore Sadar', 57),
       ('Chaugachha', 57),
       ('Manirampur', 57),
       ('Jhikargachha', 57),
       ('Sharsha', 57),
       ('Jhenaidah Sadar', 58),
       ('Maheshpur', 58),
       ('Kaliganj', 58),
       ('Kotchandpur', 58),
       ('Shailkupa', 58),
       ('Harinakunda', 58),
       ('Terokhada', 59),
       ('Batiaghata', 59),
       ('Dacope', 59),
       ('Dumuria', 59),
       ('Dighalia', 59),
       ('Koyra', 59),
       ('Paikgachha', 59),
       ('Phultala', 59),
       ('Rupsa', 59),
       ('Kushtia Sadar', 60),
       ('Kumarkhali', 60),
       ('Daulatpur', 60),
       ('Mirpur', 60),
       ('Bheramara', 60),
       ('Khoksa', 60),
       ('Magura Sadar', 61),
       ('Mohammadpur', 61),
       ('Shalikha', 61),
       ('Sreepur', 61),
       ('angni', 62),
       ('Mujib Nagar', 62),
       ('Meherpur-S', 62),
       ('Narail-S Upazilla', 63),
       ('Lohagara Upazilla', 63),
       ('Kalia Upazilla', 63),
       ('Satkhira Sadar', 64),
       ('Assasuni', 64),
       ('Debhata', 64),
       ('Tala', 64),
       ('Kalaroa', 64),
       ('Kaliganj', 64),
       ('Shyamnagar', 64),
       ('Adamdighi', 18),
       ('Bogra Sadar', 18),
       ('Sherpur', 18),
       ('Dhunat', 18),
       ('Dhupchanchia', 18),
       ('Gabtali', 18),
       ('Kahaloo', 18),
       ('Nandigram', 18),
       ('Sahajanpur', 18),
       ('Sariakandi', 18),
       ('Shibganj', 18),
       ('Sonatala', 18),
       ('Joypurhat S', 19),
       ('Akkelpur', 19),
       ('Kalai', 19),
       ('Khetlal', 19),
       ('Panchbibi', 19),
       ('Naogaon Sadar', 20),
       ('Mohadevpur', 20),
       ('Manda', 20),
       ('Niamatpur', 20),
       ('Atrai', 20),
       ('Raninagar', 20),
       ('Patnitala', 20),
       ('Dhamoirhat', 20),
       ('Sapahar', 20),
       ('Porsha', 20),
       ('Badalgachhi', 20),
       ('Natore Sadar', 21),
       ('Baraigram', 21),
       ('Bagatipara', 21),
       ('Lalpur', 21),
       ('Natore Sadar', 21),
       ('Baraigram', 21),
       ('Bholahat', 22),
       ('Gomastapur', 22),
       ('Nachole', 22),
       ('Nawabganj Sadar', 22),
       ('Shibganj', 22),
       ('Atgharia', 23),
       ('Bera', 23),
       ('Bhangura', 23),
       ('Chatmohar', 23),
       ('Faridpur', 23),
       ('Ishwardi', 23),
       ('Pabna Sadar', 23),
       ('Santhia', 23),
       ('Sujanagar', 23),
       ('Bagha', 24),
       ('Bagmara', 24),
       ('Charghat', 24),
       ('Durgapur', 24),
       ('Godagari', 24),
       ('Mohanpur', 24),
       ('Paba', 24),
       ('Puthia', 24),
       ('Tanore', 24),
       ('Sirajganj Sadar', 25),
       ('Belkuchi', 25),
       ('Chauhali', 25),
       ('Kamarkhanda', 25),
       ('Kazipur', 25),
       ('Raiganj', 25),
       ('Shahjadpur', 25),
       ('Tarash', 25),
       ('Ullahpara', 25),
       ('Birampur', 26),
       ('Birganj', 26),
       ('Biral', 26),
       ('Bochaganj', 26),
       ('Chirirbandar', 26),
       ('Phulbari', 26),
       ('Ghoraghat', 26),
       ('Hakimpur', 26),
       ('Kaharole', 26),
       ('Khansama', 26),
       ('Dinajpur Sadar', 26),
       ('Nawabganj', 26),
       ('Parbatipur', 26),
       ('Fulchhari', 27),
       ('Gaibandha sadar', 27),
       ('Gobindaganj', 27),
       ('Palashbari', 27),
       ('Sadullapur', 27),
       ('Saghata', 27),
       ('Sundarganj', 27),
       ('Kurigram Sadar', 28),
       ('Nageshwari', 28),
       ('Bhurungamari', 28),
       ('Phulbari', 28),
       ('Rajarhat', 28),
       ('Ulipur', 28),
       ('Chilmari', 28),
       ('Rowmari', 28),
       ('Char Rajibpur', 28),
       ('Lalmanirhat Sadar', 29),
       ('Aditmari', 29),
       ('Kaliganj', 29),
       ('Hatibandha', 29),
       ('Patgram', 29),
       ('Nilphamari Sadar', 30),
       ('Saidpur', 30),
       ('Jaldhaka', 30),
       ('Kishoreganj', 30),
       ('Domar', 30),
       ('Dimla', 30),
       ('Panchagarh Sadar', 31),
       ('Debiganj', 31),
       ('Boda', 31),
       ('Atwari', 31),
       ('Tetulia', 31),
       ('Badarganj', 32),
       ('Mithapukur', 32),
       ('Gangachara', 32),
       ('Kaunia', 32),
       ('Rangpur Sadar', 32),
       ('Pirgachha', 32),
       ('Pirganj', 32),
       ('Taraganj', 32),
       ('Thakurgaon Sadar', 33),
       ('Pirganj', 33),
       ('Baliadangi', 33),
       ('Haripur', 33),
       ('Ranisankail', 33),
       ('Ajmiriganj', 51),
       ('Baniachang', 51),
       ('Bahubal', 51),
       ('Chunarughat', 51),
       ('Habiganj Sadar', 51),
       ('Lakhai', 51),
       ('Madhabpur', 51),
       ('Nabiganj', 51),
       ('Shaistagonj', 51),
       ('Moulvibazar Sadar', 52),
       ('Barlekha', 52),
       ('Juri', 52),
       ('Kamalganj', 52),
       ('Kulaura', 52),
       ('Rajnagar', 52),
       ('Sreemangal', 52),
       ('Bishwamvarpur', 53),
       ('Chhatak', 53),
       ('Derai', 53),
       ('Dharampasha', 53),
       ('Dowarabazar', 53),
       ('Jagannathpur', 53),
       ('Jamalganj', 53),
       ('Sulla', 53),
       ('Sunamganj Sadar', 53),
       ('Shanthiganj', 53),
       ('Tahirpur', 53),
       ('Sylhet Sadar', 54),
       ('Beanibazar', 54),
       ('Bishwanath', 54),
       ('Dakshin Surma', 54),
       ('Balaganj', 54),
       ('Companiganj', 54),
       ('Fenchuganj', 54),
       ('Golapganj', 54),
       ('Gowainghat', 54),
       ('Jointapur', 54),
       ('Kanaighat', 54),
       ('Zakiganj', 54),
       ('Nobigonj', 54),
       ('Eidgaon', 45),
       ('Modhyanagar', 53),
       ('Dasar', 7);