// src/stores/areaLocationStore.ts
import { create } from 'zustand';

export interface Division {
  id: number;
  name: string;
}

export interface District {
  id: number;
  name: string;
  division_id: number;
}

export interface Upazila {
  id: number;
  name: string;
  district_id: number;
}

interface LocationStore {
  divisions: Division[];
  districts: District[];
  upazilas: Upazila[];
  getDistrictsByDivision: (divisionId: number) => District[];
  getUpazilasByDistrict: (districtId: number) => Upazila[];
}

// Complete data from the SQL file
const divisionsData: Division[] = [
  { id: 1, name: 'Barisal' },
  { id: 2, name: 'Chattogram' },
  { id: 3, name: 'Dhaka' },
  { id: 4, name: 'Khulna' },
  { id: 5, name: 'Rajshahi' },
  { id: 6, name: 'Rangpur' },
  { id: 7, name: 'Sylhet' },
  { id: 8, name: 'Mymensingh' }
];

const districtsData: District[] = [
  { id: 1, name: 'Dhaka', division_id: 3 },
  { id: 2, name: 'Faridpur', division_id: 3 },
  { id: 3, name: 'Gazipur', division_id: 3 },
  { id: 4, name: 'Gopalganj', division_id: 3 },
  { id: 5, name: 'Jamalpur', division_id: 8 },
  { id: 6, name: 'Kishoreganj', division_id: 3 },
  { id: 7, name: 'Madaripur', division_id: 3 },
  { id: 8, name: 'Manikganj', division_id: 3 },
  { id: 9, name: 'Munshiganj', division_id: 3 },
  { id: 10, name: 'Mymensingh', division_id: 8 },
  { id: 11, name: 'Narayanganj', division_id: 3 },
  { id: 12, name: 'Narsingdi', division_id: 3 },
  { id: 13, name: 'Netrokona', division_id: 8 },
  { id: 14, name: 'Rajbari', division_id: 3 },
  { id: 15, name: 'Shariatpur', division_id: 3 },
  { id: 16, name: 'Sherpur', division_id: 8 },
  { id: 17, name: 'Tangail', division_id: 3 },
  { id: 18, name: 'Bogura', division_id: 5 },
  { id: 19, name: 'Joypurhat', division_id: 5 },
  { id: 20, name: 'Naogaon', division_id: 5 },
  { id: 21, name: 'Natore', division_id: 5 },
  { id: 22, name: 'Nawabganj', division_id: 5 },
  { id: 23, name: 'Pabna', division_id: 5 },
  { id: 24, name: 'Rajshahi', division_id: 5 },
  { id: 25, name: 'Sirajgonj', division_id: 5 },
  { id: 26, name: 'Dinajpur', division_id: 6 },
  { id: 27, name: 'Gaibandha', division_id: 6 },
  { id: 28, name: 'Kurigram', division_id: 6 },
  { id: 29, name: 'Lalmonirhat', division_id: 6 },
  { id: 30, name: 'Nilphamari', division_id: 6 },
  { id: 31, name: 'Panchagarh', division_id: 6 },
  { id: 32, name: 'Rangpur', division_id: 6 },
  { id: 33, name: 'Thakurgaon', division_id: 6 },
  { id: 34, name: 'Barguna', division_id: 1 },
  { id: 35, name: 'Barishal', division_id: 1 },
  { id: 36, name: 'Bhola', division_id: 1 },
  { id: 37, name: 'Jhalokati', division_id: 1 },
  { id: 38, name: 'Patuakhali', division_id: 1 },
  { id: 39, name: 'Pirojpur', division_id: 1 },
  { id: 40, name: 'Bandarban', division_id: 2 },
  { id: 41, name: 'Brahmanbaria', division_id: 2 },
  { id: 42, name: 'Chandpur', division_id: 2 },
  { id: 43, name: 'Chattogram', division_id: 2 },
  { id: 44, name: 'Cumilla', division_id: 2 },
  { id: 45, name: 'Cox\'s Bazar', division_id: 2 },
  { id: 46, name: 'Feni', division_id: 2 },
  { id: 47, name: 'Khagrachari', division_id: 2 },
  { id: 48, name: 'Lakshmipur', division_id: 2 },
  { id: 49, name: 'Noakhali', division_id: 2 },
  { id: 50, name: 'Rangamati', division_id: 2 },
  { id: 51, name: 'Habiganj', division_id: 7 },
  { id: 52, name: 'Maulvibazar', division_id: 7 },
  { id: 53, name: 'Sunamganj', division_id: 7 },
  { id: 54, name: 'Sylhet', division_id: 7 },
  { id: 55, name: 'Bagerhat', division_id: 4 },
  { id: 56, name: 'Chuadanga', division_id: 4 },
  { id: 57, name: 'Jashore', division_id: 4 },
  { id: 58, name: 'Jhenaidah', division_id: 4 },
  { id: 59, name: 'Khulna', division_id: 4 },
  { id: 60, name: 'Kushtia', division_id: 4 },
  { id: 61, name: 'Magura', division_id: 4 },
  { id: 62, name: 'Meherpur', division_id: 4 },
  { id: 63, name: 'Narail', division_id: 4 },
  { id: 64, name: 'Satkhira', division_id: 4 }
];

const upazilasData: Upazila[] = [
  { id: 1, name: 'Amtali', district_id: 34 },
  { id: 2, name: 'Bamna', district_id: 34 },
  { id: 3, name: 'Barguna Sadar', district_id: 34 },
  { id: 4, name: 'Betagi', district_id: 34 },
  { id: 5, name: 'Patharghata', district_id: 34 },
  { id: 6, name: 'Taltali', district_id: 34 },
  { id: 7, name: 'Muladi', district_id: 35 },
  { id: 8, name: 'Babuganj', district_id: 35 },
  { id: 9, name: 'Agailjhara', district_id: 35 },
  { id: 10, name: 'Barisal Sadar', district_id: 35 },
  { id: 11, name: 'Bakerganj', district_id: 35 },
  { id: 12, name: 'Banaripara', district_id: 35 },
  { id: 13, name: 'Gaurnadi', district_id: 35 },
  { id: 14, name: 'Hizla', district_id: 35 },
  { id: 15, name: 'Mehendiganj', district_id: 35 },
  { id: 16, name: 'Wazirpur', district_id: 35 },
  { id: 17, name: 'Bhola Sadar', district_id: 36 },
  { id: 18, name: 'Burhanuddin', district_id: 36 },
  { id: 19, name: 'Char Fasson', district_id: 36 },
  { id: 20, name: 'Daulatkhan', district_id: 36 },
  { id: 21, name: 'Lalmohan', district_id: 36 },
  { id: 22, name: 'Manpura', district_id: 36 },
  { id: 23, name: 'Tazumuddin', district_id: 36 },
  { id: 24, name: 'Jhalokati Sadar', district_id: 37 },
  { id: 25, name: 'Kathalia', district_id: 37 },
  { id: 26, name: 'Nalchity', district_id: 37 },
  { id: 27, name: 'Rajapur', district_id: 37 },
  { id: 28, name: 'Bauphal', district_id: 38 },
  { id: 29, name: 'Dashmina', district_id: 38 },
  { id: 30, name: 'Galachipa', district_id: 38 },
  { id: 31, name: 'Kalapara', district_id: 38 },
  { id: 32, name: 'Mirzaganj', district_id: 38 },
  { id: 33, name: 'Patuakhali Sadar', district_id: 38 },
  { id: 34, name: 'Dumki', district_id: 38 },
  { id: 35, name: 'Rangabali', district_id: 38 },
  { id: 36, name: 'Bhandaria', district_id: 39 },
  { id: 37, name: 'Kaukhali', district_id: 39 },
  { id: 38, name: 'Mathbaria', district_id: 39 },
  { id: 39, name: 'Nazirpur', district_id: 39 },
  { id: 40, name: 'Nesarabad', district_id: 39 },
  { id: 41, name: 'Pirojpur Sadar', district_id: 39 },
  { id: 42, name: 'Zianagar', district_id: 39 },
  { id: 43, name: 'Bandarban Sadar', district_id: 40 },
  { id: 44, name: 'Thanchi', district_id: 40 },
  { id: 45, name: 'Lama', district_id: 40 },
  { id: 46, name: 'Naikhongchhari', district_id: 40 },
  { id: 47, name: 'Ali kadam', district_id: 40 },
  { id: 48, name: 'Rowangchhari', district_id: 40 },
  { id: 49, name: 'Ruma', district_id: 40 },
  { id: 50, name: 'Brahmanbaria Sadar', district_id: 41 },
  { id: 51, name: 'Ashuganj', district_id: 41 },
  { id: 52, name: 'Nasirnagar', district_id: 41 },
  { id: 53, name: 'Nabinagar', district_id: 41 },
  { id: 54, name: 'Sarail', district_id: 41 },
  { id: 55, name: 'Shahbazpur Town', district_id: 41 },
  { id: 56, name: 'Kasba', district_id: 41 },
  { id: 57, name: 'Akhaura', district_id: 41 },
  { id: 58, name: 'Bancharampur', district_id: 41 },
  { id: 59, name: 'Bijoynagar', district_id: 41 },
  { id: 60, name: 'Chandpur Sadar', district_id: 42 },
  { id: 61, name: 'Faridganj', district_id: 42 },
  { id: 62, name: 'Haimchar', district_id: 42 },
  { id: 63, name: 'Haziganj', district_id: 42 },
  { id: 64, name: 'Kachua', district_id: 42 },
  { id: 65, name: 'Matlab Uttar', district_id: 42 },
  { id: 66, name: 'Matlab Dakkhin', district_id: 42 },
  { id: 67, name: 'Shahrasti', district_id: 42 },
  { id: 68, name: 'Anwara', district_id: 43 },
  { id: 69, name: 'Banshkhali', district_id: 43 },
  { id: 70, name: 'Boalkhali', district_id: 43 },
  { id: 71, name: 'Chandanaish', district_id: 43 },
  { id: 72, name: 'Fatikchhari', district_id: 43 },
  { id: 73, name: 'Hathazari', district_id: 43 },
  { id: 74, name: 'Lohagara', district_id: 43 },
  { id: 75, name: 'Mirsharai', district_id: 43 },
  { id: 76, name: 'Patiya', district_id: 43 },
  { id: 77, name: 'Rangunia', district_id: 43 },
  { id: 78, name: 'Raozan', district_id: 43 },
  { id: 79, name: 'Sandwip', district_id: 43 },
  { id: 80, name: 'Satkania', district_id: 43 },
  { id: 81, name: 'Sitakunda', district_id: 43 },
  { id: 82, name: 'Barura', district_id: 44 },
  { id: 83, name: 'Brahmanpara', district_id: 44 },
  { id: 84, name: 'Burichong', district_id: 44 },
  { id: 85, name: 'Chandina', district_id: 44 },
  { id: 86, name: 'Chauddagram', district_id: 44 },
  { id: 87, name: 'Daudkandi', district_id: 44 },
  { id: 88, name: 'Debidwar', district_id: 44 },
  { id: 89, name: 'Homna', district_id: 44 },
  { id: 90, name: 'Comilla Sadar', district_id: 44 },
  { id: 91, name: 'Laksam', district_id: 44 },
  { id: 92, name: 'Monohorgonj', district_id: 44 },
  { id: 93, name: 'Meghna', district_id: 44 },
  { id: 94, name: 'Muradnagar', district_id: 44 },
  { id: 95, name: 'Nangalkot', district_id: 44 },
  { id: 96, name: 'Comilla Sadar South', district_id: 44 },
  { id: 97, name: 'Titas', district_id: 44 },
  { id: 98, name: 'Chakaria', district_id: 45 },
  { id: 99, name: 'Cox\'s Bazar Sadar', district_id: 45 },
  { id: 100, name: 'Kutubdia', district_id: 45 },
  { id: 101, name: 'Maheshkhali', district_id: 45 },
  { id: 102, name: 'Ramu', district_id: 45 },
  { id: 103, name: 'Teknaf', district_id: 45 },
  { id: 104, name: 'Ukhia', district_id: 45 },
  { id: 105, name: 'Pekua', district_id: 45 },
  { id: 106, name: 'Feni Sadar', district_id: 46 },
  { id: 107, name: 'Chagalnaiya', district_id: 46 },
  { id: 108, name: 'Daganbhyan', district_id: 46 },
  { id: 109, name: 'Parshuram', district_id: 46 },
  { id: 110, name: 'Fhulgazi', district_id: 46 },
  { id: 111, name: 'Sonagazi', district_id: 46 },
  { id: 112, name: 'Dighinala', district_id: 47 },
  { id: 113, name: 'Khagrachhari', district_id: 47 },
  { id: 114, name: 'Lakshmichhari', district_id: 47 },
  { id: 115, name: 'Mahalchhari', district_id: 47 },
  { id: 116, name: 'Manikchhari', district_id: 47 },
  { id: 117, name: 'Matiranga', district_id: 47 },
  { id: 118, name: 'Panchhari', district_id: 47 },
  { id: 119, name: 'Ramgarh', district_id: 47 },
  { id: 120, name: 'Lakshmipur Sadar', district_id: 48 },
  { id: 121, name: 'Raipur', district_id: 48 },
  { id: 122, name: 'Ramganj', district_id: 48 },
  { id: 123, name: 'Ramgati', district_id: 48 },
  { id: 124, name: 'Komol Nagar', district_id: 48 },
  { id: 125, name: 'Noakhali Sadar', district_id: 49 },
  { id: 126, name: 'Begumganj', district_id: 49 },
  { id: 127, name: 'Chatkhil', district_id: 49 },
  { id: 128, name: 'Companyganj', district_id: 49 },
  { id: 129, name: 'Shenbag', district_id: 49 },
  { id: 130, name: 'Hatia', district_id: 49 },
  { id: 131, name: 'Kobirhat', district_id: 49 },
  { id: 132, name: 'Sonaimuri', district_id: 49 },
  { id: 133, name: 'Suborno Char', district_id: 49 },
  { id: 134, name: 'Rangamati Sadar', district_id: 50 },
  { id: 135, name: 'Belaichhari', district_id: 50 },
  { id: 136, name: 'Bagaichhari', district_id: 50 },
  { id: 137, name: 'Barkal', district_id: 50 },
  { id: 138, name: 'Juraichhari', district_id: 50 },
  { id: 139, name: 'Rajasthali', district_id: 50 },
  { id: 140, name: 'Kaptai', district_id: 50 },
  { id: 141, name: 'Langadu', district_id: 50 },
  { id: 142, name: 'Nannerchar', district_id: 50 },
  { id: 143, name: 'Kaukhali', district_id: 50 },
  { id: 144, name: 'Dhamrai', district_id: 1 },
  { id: 145, name: 'Dohar', district_id: 1 },
  { id: 146, name: 'Keraniganj', district_id: 1 },
  { id: 147, name: 'Nawabganj', district_id: 1 },
  { id: 148, name: 'Savar', district_id: 1 },
  { id: 149, name: 'Faridpur Sadar', district_id: 2 },
  { id: 150, name: 'Boalmari', district_id: 2 },
  { id: 151, name: 'Alfadanga', district_id: 2 },
  { id: 152, name: 'Madhukhali', district_id: 2 },
  { id: 153, name: 'Bhanga', district_id: 2 },
  { id: 154, name: 'Nagarkanda', district_id: 2 },
  { id: 155, name: 'Charbhadrasan', district_id: 2 },
  { id: 156, name: 'Sadarpur', district_id: 2 },
  { id: 157, name: 'Shaltha', district_id: 2 },
  { id: 158, name: 'Gazipur Sadar-Joydebpur', district_id: 3 },
  { id: 159, name: 'Kaliakior', district_id: 3 },
  { id: 160, name: 'Kapasia', district_id: 3 },
  { id: 161, name: 'Sripur', district_id: 3 },
  { id: 162, name: 'Kaliganj', district_id: 3 },
  { id: 163, name: 'Tongi', district_id: 3 },
  { id: 164, name: 'Gopalganj Sadar', district_id: 4 },
  { id: 165, name: 'Kashiani', district_id: 4 },
  { id: 166, name: 'Kotalipara', district_id: 4 },
  { id: 167, name: 'Muksudpur', district_id: 4 },
  { id: 168, name: 'Tungipara', district_id: 4 },
  { id: 169, name: 'Dewanganj', district_id: 5 },
  { id: 170, name: 'Baksiganj', district_id: 5 },
  { id: 171, name: 'Islampur', district_id: 5 },
  { id: 172, name: 'Jamalpur Sadar', district_id: 5 },
  { id: 173, name: 'Madarganj', district_id: 5 },
  { id: 174, name: 'Melandaha', district_id: 5 },
  { id: 175, name: 'Sarishabari', district_id: 5 },
  { id: 176, name: 'Narundi Police I.C', district_id: 5 },
  { id: 177, name: 'Astagram', district_id: 6 },
  { id: 178, name: 'Bajitpur', district_id: 6 },
  { id: 179, name: 'Bhairab', district_id: 6 },
  { id: 180, name: 'Hossainpur', district_id: 6 },
  { id: 181, name: 'Itna', district_id: 6 },
  { id: 182, name: 'Karimganj', district_id: 6 },
  { id: 183, name: 'Katiadi', district_id: 6 },
  { id: 184, name: 'Kishoreganj Sadar', district_id: 6 },
  { id: 185, name: 'Kuliarchar', district_id: 6 },
  { id: 186, name: 'Mithamain', district_id: 6 },
  { id: 187, name: 'Nikli', district_id: 6 },
  { id: 188, name: 'Pakundia', district_id: 6 },
  { id: 189, name: 'Tarail', district_id: 6 },
  { id: 190, name: 'Madaripur Sadar', district_id: 7 },
  { id: 191, name: 'Kalkini', district_id: 7 },
  { id: 192, name: 'Rajoir', district_id: 7 },
  { id: 193, name: 'Shibchar', district_id: 7 },
  { id: 194, name: 'Manikganj Sadar', district_id: 8 },
  { id: 195, name: 'Singair', district_id: 8 },
  { id: 196, name: 'Shibalaya', district_id: 8 },
  { id: 197, name: 'Saturia', district_id: 8 },
  { id: 198, name: 'Harirampur', district_id: 8 },
  { id: 199, name: 'Ghior', district_id: 8 },
  { id: 200, name: 'Daulatpur', district_id: 8 },
  { id: 201, name: 'Lohajang', district_id: 9 },
  { id: 202, name: 'Sreenagar', district_id: 9 },
  { id: 203, name: 'Munshiganj Sadar', district_id: 9 },
  { id: 204, name: 'Sirajdikhan', district_id: 9 },
  { id: 205, name: 'Tongibari', district_id: 9 },
  { id: 206, name: 'Gazaria', district_id: 9 },
  { id: 207, name: 'Bhaluka', district_id: 10 },
  { id: 208, name: 'Trishal', district_id: 10 },
  { id: 209, name: 'Haluaghat', district_id: 10 },
  { id: 210, name: 'Muktagachha', district_id: 10 },
  { id: 211, name: 'Dhobaura', district_id: 10 },
  { id: 212, name: 'Fulbaria', district_id: 10 },
  { id: 213, name: 'Gaffargaon', district_id: 10 },
  { id: 214, name: 'Gauripur', district_id: 10 },
  { id: 215, name: 'Ishwarganj', district_id: 10 },
  { id: 216, name: 'Mymensingh Sadar', district_id: 10 },
  { id: 217, name: 'Nandail', district_id: 10 },
  { id: 218, name: 'Phulpur', district_id: 10 },
  { id: 219, name: 'Araihazar', district_id: 11 },
  { id: 220, name: 'Sonargaon', district_id: 11 },
  { id: 221, name: 'Bandar', district_id: 11 },
  { id: 222, name: 'Naryanganj Sadar', district_id: 11 },
  { id: 223, name: 'Rupganj', district_id: 11 },
  { id: 224, name: 'Siddirgonj', district_id: 11 },
  { id: 225, name: 'Belabo', district_id: 12 },
  { id: 226, name: 'Monohardi', district_id: 12 },
  { id: 227, name: 'Narsingdi Sadar', district_id: 12 },
  { id: 228, name: 'Palash', district_id: 12 },
  { id: 229, name: 'Raipura, Narsingdi', district_id: 12 },
  { id: 230, name: 'Shibpur', district_id: 12 },
  { id: 231, name: 'Kendua Upazilla', district_id: 13 },
  { id: 232, name: 'Atpara Upazilla', district_id: 13 },
  { id: 233, name: 'Barhatta Upazilla', district_id: 13 },
  { id: 234, name: 'Durgapur Upazilla', district_id: 13 },
  { id: 235, name: 'Kalmakanda Upazilla', district_id: 13 },
  { id: 236, name: 'Madan Upazilla', district_id: 13 },
  { id: 237, name: 'Mohanganj Upazilla', district_id: 13 },
  { id: 238, name: 'Netrakona-S Upazilla', district_id: 13 },
  { id: 239, name: 'Purbadhala Upazilla', district_id: 13 },
  { id: 240, name: 'Khaliajuri Upazilla', district_id: 13 },
  { id: 241, name: 'Baliakandi', district_id: 14 },
  { id: 242, name: 'Goalandaghat', district_id: 14 },
  { id: 243, name: 'Pangsha', district_id: 14 },
  { id: 244, name: 'Kalukhali', district_id: 14 },
  { id: 245, name: 'Rajbari Sadar', district_id: 14 },
  { id: 246, name: 'Shariatpur Sadar -Palong', district_id: 15 },
  { id: 247, name: 'Damudya', district_id: 15 },
  { id: 248, name: 'Naria', district_id: 15 },
  { id: 249, name: 'Jajira', district_id: 15 },
  { id: 250, name: 'Bhedarganj', district_id: 15 },
  { id: 251, name: 'Gosairhat', district_id: 15 },
  { id: 252, name: 'Jhenaigati', district_id: 16 },
  { id: 253, name: 'Nakla', district_id: 16 },
  { id: 254, name: 'Nalitabari', district_id: 16 },
  { id: 255, name: 'Sherpur Sadar', district_id: 16 },
  { id: 256, name: 'Sreebardi', district_id: 16 },
  { id: 257, name: 'Tangail Sadar', district_id: 17 },
  { id: 258, name: 'Sakhipur', district_id: 17 },
  { id: 259, name: 'Basail', district_id: 17 },
  { id: 260, name: 'Madhupur', district_id: 17 },
  { id: 261, name: 'Ghatail', district_id: 17 },
  { id: 262, name: 'Kalihati', district_id: 17 },
  { id: 263, name: 'Nagarpur', district_id: 17 },
  { id: 264, name: 'Mirzapur', district_id: 17 },
  { id: 265, name: 'Gopalpur', district_id: 17 },
  { id: 266, name: 'Delduar', district_id: 17 },
  { id: 267, name: 'Bhuapur', district_id: 17 },
  { id: 268, name: 'Dhanbari', district_id: 17 },
  { id: 269, name: 'Bagerhat Sadar', district_id: 55 },
  { id: 270, name: 'Chitalmari', district_id: 55 },
  { id: 271, name: 'Fakirhat', district_id: 55 },
  { id: 272, name: 'Kachua', district_id: 55 },
  { id: 273, name: 'Mollahat', district_id: 55 },
  { id: 274, name: 'Mongla', district_id: 55 },
  { id: 275, name: 'Morrelganj', district_id: 55 },
  { id: 276, name: 'Rampal', district_id: 55 },
  { id: 277, name: 'Sarankhola', district_id: 55 },
  { id: 278, name: 'Damurhuda', district_id: 56 },
  { id: 279, name: 'Chuadanga-S', district_id: 56 },
  { id: 280, name: 'Jibannagar', district_id: 56 },
  { id: 281, name: 'Alamdanga', district_id: 56 },
  { id: 282, name: 'Abhaynagar', district_id: 57 },
  { id: 283, name: 'Keshabpur', district_id: 57 },
  { id: 284, name: 'Bagherpara', district_id: 57 },
  { id: 285, name: 'Jessore Sadar', district_id: 57 },
  { id: 286, name: 'Chaugachha', district_id: 57 },
  { id: 287, name: 'Manirampur', district_id: 57 },
  { id: 288, name: 'Jhikargachha', district_id: 57 },
  { id: 289, name: 'Sharsha', district_id: 57 },
  { id: 290, name: 'Jhenaidah Sadar', district_id: 58 },
  { id: 291, name: 'Maheshpur', district_id: 58 },
  { id: 292, name: 'Kaliganj', district_id: 58 },
  { id: 293, name: 'Kotchandpur', district_id: 58 },
  { id: 294, name: 'Shailkupa', district_id: 58 },
  { id: 295, name: 'Harinakunda', district_id: 58 },
  { id: 296, name: 'Terokhada', district_id: 59 },
  { id: 297, name: 'Batiaghata', district_id: 59 },
  { id: 298, name: 'Dacope', district_id: 59 },
  { id: 299, name: 'Dumuria', district_id: 59 },
  { id: 300, name: 'Dighalia', district_id: 59 },
  { id: 301, name: 'Koyra', district_id: 59 },
  { id: 302, name: 'Paikgachha', district_id: 59 },
  { id: 303, name: 'Phultala', district_id: 59 },
  { id: 304, name: 'Rupsa', district_id: 59 },
  { id: 305, name: 'Kushtia Sadar', district_id: 60 },
  { id: 306, name: 'Kumarkhali', district_id: 60 },
  { id: 307, name: 'Daulatpur', district_id: 60 },
  { id: 308, name: 'Mirpur', district_id: 60 },
  { id: 309, name: 'Bheramara', district_id: 60 },
  { id: 310, name: 'Khoksa', district_id: 60 },
  { id: 311, name: 'Magura Sadar', district_id: 61 },
  { id: 312, name: 'Mohammadpur', district_id: 61 },
  { id: 313, name: 'Shalikha', district_id: 61 },
  { id: 314, name: 'Sreepur', district_id: 61 },
  { id: 315, name: 'Gangni', district_id: 62 }, // Fixed 'angni' to 'Gangni'
  { id: 316, name: 'Mujib Nagar', district_id: 62 },
  { id: 317, name: 'Meherpur-S', district_id: 62 },
  { id: 318, name: 'Narail-S Upazilla', district_id: 63 },
  { id: 319, name: 'Lohagara Upazilla', district_id: 63 },
  { id: 320, name: 'Kalia Upazilla', district_id: 63 },
  { id: 321, name: 'Satkhira Sadar', district_id: 64 },
  { id: 322, name: 'Assasuni', district_id: 64 },
  { id: 323, name: 'Debhata', district_id: 64 },
  { id: 324, name: 'Tala', district_id: 64 },
  { id: 325, name: 'Kalaroa', district_id: 64 },
  { id: 326, name: 'Kaliganj', district_id: 64 },
  { id: 327, name: 'Shyamnagar', district_id: 64 },
  { id: 328, name: 'Adamdighi', district_id: 18 },
  { id: 329, name: 'Bogra Sadar', district_id: 18 },
  { id: 330, name: 'Sherpur', district_id: 18 },
  { id: 331, name: 'Dhunat', district_id: 18 },
  { id: 332, name: 'Dhupchanchia', district_id: 18 },
  { id: 333, name: 'Gabtali', district_id: 18 },
  { id: 334, name: 'Kahaloo', district_id: 18 },
  { id: 335, name: 'Nandigram', district_id: 18 },
  { id: 336, name: 'Sahajanpur', district_id: 18 },
  { id: 337, name: 'Sariakandi', district_id: 18 },
  { id: 338, name: 'Shibganj', district_id: 18 },
  { id: 339, name: 'Sonatala', district_id: 18 },
  { id: 340, name: 'Joypurhat S', district_id: 19 },
  { id: 341, name: 'Akkelpur', district_id: 19 },
  { id: 342, name: 'Kalai', district_id: 19 },
  { id: 343, name: 'Khetlal', district_id: 19 },
  { id: 344, name: 'Panchbibi', district_id: 19 },
  { id: 345, name: 'Naogaon Sadar', district_id: 20 },
  { id: 346, name: 'Mohadevpur', district_id: 20 },
  { id: 347, name: 'Manda', district_id: 20 },
  { id: 348, name: 'Niamatpur', district_id: 20 },
  { id: 349, name: 'Atrai', district_id: 20 },
  { id: 350, name: 'Raninagar', district_id: 20 },
  { id: 351, name: 'Patnitala', district_id: 20 },
  { id: 352, name: 'Dhamoirhat', district_id: 20 },
  { id: 353, name: 'Sapahar', district_id: 20 },
  { id: 354, name: 'Porsha', district_id: 20 },
  { id: 355, name: 'Badalgachhi', district_id: 20 },
  { id: 356, name: 'Natore Sadar', district_id: 21 },
  { id: 357, name: 'Baraigram', district_id: 21 },
  { id: 358, name: 'Bagatipara', district_id: 21 },
  { id: 359, name: 'Lalpur', district_id: 21 },
  { id: 360, name: 'Singra', district_id: 21 }, // Added to replace duplicate entries
  { id: 361, name: 'Gurudaspur', district_id: 21 }, // Added to replace duplicate entries
  { id: 362, name: 'Bholahat', district_id: 22 },
  { id: 363, name: 'Gomastapur', district_id: 22 },
  { id: 364, name: 'Nachole', district_id: 22 },
  { id: 365, name: 'Nawabganj Sadar', district_id: 22 },
  { id: 366, name: 'Shibganj', district_id: 22 },
  { id: 367, name: 'Atgharia', district_id: 23 },
  { id: 368, name: 'Bera', district_id: 23 },
  { id: 369, name: 'Bhangura', district_id: 23 },
  { id: 370, name: 'Chatmohar', district_id: 23 },
  { id: 371, name: 'Faridpur', district_id: 23 },
  { id: 372, name: 'Ishwardi', district_id: 23 },
  { id: 373, name: 'Pabna Sadar', district_id: 23 },
  { id: 374, name: 'Santhia', district_id: 23 },
  { id: 375, name: 'Sujanagar', district_id: 23 },
  { id: 376, name: 'Bagha', district_id: 24 },
  { id: 377, name: 'Bagmara', district_id: 24 },
  { id: 378, name: 'Charghat', district_id: 24 },
  { id: 379, name: 'Durgapur', district_id: 24 },
  { id: 380, name: 'Godagari', district_id: 24 },
  { id: 381, name: 'Mohanpur', district_id: 24 },
  { id: 382, name: 'Paba', district_id: 24 },
  { id: 383, name: 'Puthia', district_id: 24 },
  { id: 384, name: 'Tanore', district_id: 24 },
  { id: 385, name: 'Sirajganj Sadar', district_id: 25 },
  { id: 386, name: 'Belkuchi', district_id: 25 },
  { id: 387, name: 'Chauhali', district_id: 25 },
  { id: 388, name: 'Kamarkhanda', district_id: 25 },
  { id: 389, name: 'Kazipur', district_id: 25 },
  { id: 390, name: 'Raiganj', district_id: 25 },
  { id: 391, name: 'Shahjadpur', district_id: 25 },
  { id: 392, name: 'Tarash', district_id: 25 },
  { id: 393, name: 'Ullahpara', district_id: 25 },
  { id: 394, name: 'Birampur', district_id: 26 },
  { id: 395, name: 'Birganj', district_id: 26 },
  { id: 396, name: 'Biral', district_id: 26 },
  { id: 397, name: 'Bochaganj', district_id: 26 },
  { id: 398, name: 'Chirirbandar', district_id: 26 },
  { id: 399, name: 'Phulbari', district_id: 26 },
  { id: 400, name: 'Ghoraghat', district_id: 26 },
  { id: 401, name: 'Hakimpur', district_id: 26 },
  { id: 402, name: 'Kaharole', district_id: 26 },
  { id: 403, name: 'Khansama', district_id: 26 },
  { id: 404, name: 'Dinajpur Sadar', district_id: 26 },
  { id: 405, name: 'Nawabganj', district_id: 26 },
  { id: 406, name: 'Parbatipur', district_id: 26 },
  { id: 407, name: 'Fulchhari', district_id: 27 },
  { id: 408, name: 'Gaibandha sadar', district_id: 27 },
  { id: 409, name: 'Gobindaganj', district_id: 27 },
  { id: 410, name: 'Palashbari', district_id: 27 },
  { id: 411, name: 'Sadullapur', district_id: 27 },
  { id: 412, name: 'Saghata', district_id: 27 },
  { id: 413, name: 'Sundarganj', district_id: 27 },
  { id: 414, name: 'Kurigram Sadar', district_id: 28 },
  { id: 415, name: 'Nageshwari', district_id: 28 },
  { id: 416, name: 'Bhurungamari', district_id: 28 },
  { id: 417, name: 'Phulbari', district_id: 28 },
  { id: 418, name: 'Rajarhat', district_id: 28 },
  { id: 419, name: 'Ulipur', district_id: 28 },
  { id: 420, name: 'Chilmari', district_id: 28 },
  { id: 421, name: 'Rowmari', district_id: 28 },
  { id: 422, name: 'Char Rajibpur', district_id: 28 },
  { id: 423, name: 'Lalmanirhat Sadar', district_id: 29 },
  { id: 424, name: 'Aditmari', district_id: 29 },
  { id: 425, name: 'Kaliganj', district_id: 29 },
  { id: 426, name: 'Hatibandha', district_id: 29 },
  { id: 427, name: 'Patgram', district_id: 29 },
  { id: 428, name: 'Nilphamari Sadar', district_id: 30 },
  { id: 429, name: 'Saidpur', district_id: 30 },
  { id: 430, name: 'Jaldhaka', district_id: 30 },
  { id: 431, name: 'Kishoreganj', district_id: 30 },
  { id: 432, name: 'Domar', district_id: 30 },
  { id: 433, name: 'Dimla', district_id: 30 },
  { id: 434, name: 'Panchagarh Sadar', district_id: 31 },
  { id: 435, name: 'Debiganj', district_id: 31 },
  { id: 436, name: 'Boda', district_id: 31 },
  { id: 437, name: 'Atwari', district_id: 31 },
  { id: 438, name: 'Tetulia', district_id: 31 },
  { id: 439, name: 'Badarganj', district_id: 32 },
  { id: 440, name: 'Mithapukur', district_id: 32 },
  { id: 441, name: 'Gangachara', district_id: 32 },
  { id: 442, name: 'Kaunia', district_id: 32 },
  { id: 443, name: 'Rangpur Sadar', district_id: 32 },
  { id: 444, name: 'Pirgachha', district_id: 32 },
  { id: 445, name: 'Pirganj', district_id: 32 },
  { id: 446, name: 'Taraganj', district_id: 32 },
  { id: 447, name: 'Thakurgaon Sadar', district_id: 33 },
  { id: 448, name: 'Pirganj', district_id: 33 },
  { id: 449, name: 'Baliadangi', district_id: 33 },
  { id: 450, name: 'Haripur', district_id: 33 },
  { id: 451, name: 'Ranisankail', district_id: 33 },
  { id: 452, name: 'Ajmiriganj', district_id: 51 },
  { id: 453, name: 'Baniachang', district_id: 51 },
  { id: 454, name: 'Bahubal', district_id: 51 },
  { id: 455, name: 'Chunarughat', district_id: 51 },
  { id: 456, name: 'Habiganj Sadar', district_id: 51 },
  { id: 457, name: 'Lakhai', district_id: 51 },
  { id: 458, name: 'Madhabpur', district_id: 51 },
  { id: 459, name: 'Nabiganj', district_id: 51 },
  { id: 460, name: 'Shaistagonj', district_id: 51 },
  { id: 461, name: 'Moulvibazar Sadar', district_id: 52 },
  { id: 462, name: 'Barlekha', district_id: 52 },
  { id: 463, name: 'Juri', district_id: 52 },
  { id: 464, name: 'Kamalganj', district_id: 52 },
  { id: 465, name: 'Kulaura', district_id: 52 },
  { id: 466, name: 'Rajnagar', district_id: 52 },
  { id: 467, name: 'Sreemangal', district_id: 52 },
  { id: 468, name: 'Bishwamvarpur', district_id: 53 },
  { id: 469, name: 'Chhatak', district_id: 53 },
  { id: 470, name: 'Derai', district_id: 53 },
  { id: 471, name: 'Dharampasha', district_id: 53 },
  { id: 472, name: 'Dowarabazar', district_id: 53 },
  { id: 473, name: 'Jagannathpur', district_id: 53 },
  { id: 474, name: 'Jamalganj', district_id: 53 },
  { id: 475, name: 'Sulla', district_id: 53 },
  { id: 476, name: 'Sunamganj Sadar', district_id: 53 },
  { id: 477, name: 'Shanthiganj', district_id: 53 },
  { id: 478, name: 'Tahirpur', district_id: 53 },
  { id: 479, name: 'Sylhet Sadar', district_id: 54 },
  { id: 480, name: 'Beanibazar', district_id: 54 },
  { id: 481, name: 'Bishwanath', district_id: 54 },
  { id: 482, name: 'Dakshin Surma', district_id: 54 },
  { id: 483, name: 'Balaganj', district_id: 54 },
  { id: 484, name: 'Companiganj', district_id: 54 },
  { id: 485, name: 'Fenchuganj', district_id: 54 },
  { id: 486, name: 'Golapganj', district_id: 54 },
  { id: 487, name: 'Gowainghat', district_id: 54 },
  { id: 488, name: 'Jointapur', district_id: 54 },
  { id: 489, name: 'Kanaighat', district_id: 54 },
  { id: 490, name: 'Zakiganj', district_id: 54 },
  { id: 491, name: 'Nobigonj', district_id: 54 },
  { id: 492, name: 'Eidgaon', district_id: 45 },
  { id: 493, name: 'Modhyanagar', district_id: 53 },
  { id: 494, name: 'Dasar', district_id: 7 }
];

export const useLocationStore = create<LocationStore>((set, get) => ({
  divisions: divisionsData,
  districts: districtsData,
  upazilas: upazilasData,

  getDistrictsByDivision: (divisionId: number) => {
    return get().districts.filter(district => district.division_id === divisionId);
  },

  getUpazilasByDistrict: (districtId: number) => {
    return get().upazilas.filter(upazila => upazila.district_id === districtId);
  }
}));